Fix CI for Mac OS
Build ffmpeg as external project to work around missing includes:
/Users/runner/work/sdrangel/sdrangel/plugins/channelrx/demoddatv/datvideorender.cpp:282:46: error: no member named 'channels' in 'AVCodecContext'
(and similar)