perseus: fix build error
descr->firmware_downloaded is private and require perseus-in.h that is
not installed by libperseus-sdr; see]
https://github.com/Microtelecom/libperseus-sdr/blob/e390356c86e91c7972af8a64fe23e4cf681752d7/Makefile.am
line 44

/Users/rainbow/tmp/my/sdrangel/devices/perseus/deviceperseusscan.cpp:45:18: error: member access into incomplete type 'perseus_descr' (aka 'perseus_descr_ds')
if (descr->firmware_downloaded)